modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/gamerbenyt/halfheartAPI/issues/"
displayURL = "ORIGINALMODhttps://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/"
logoFile = "icon.png"
authors = "gamerben"
license = "GNU LGPLv3"

[[mods]]
modId = "half_heart_api"
version = "${version}"
displayName = "Half Heart API v1.0.0"
description = '''
An API for config screens.
'''

[[dependencies.half_heart_api]]
modId = "forge"
mandatory = true
versionRange = "[41.0.94,)"
ordering = "NONE"
side = "BOTH"
